server:
  port: 8081

web:
  domain: http://jobever.cn

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username:
    password:
    url: jdbc:mysql://:3306/blog?useSSL=true&useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC
    type: com.zaxxer.hikari.HikariDataSource

  # 上传服务
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

# 上传路径
upload:
  dir : /home/qdl/Desktop/gallery/

# 图片网络访问路径
img:
  imgURL: http://jobever.cn:8081/images/

logging:
  level:
    root: info
    com.lin: info